### PR TITLE
Add prettify symbols mapping for 0.826 font version

### PR DESCRIPTION
**Pull request by DeLaGuardo**

### CODE REVIEW

**Comment by DeLaGuardo** [comment]
No problem) I'm happy to help with the development of such a wonderful font.

**Comment by johnhamelink** [comment]
@DeLaGuardo how are you using this PR? I'm trying to use this with Spacemacs but it doesn't seem to have any effect whatsoever - I am sure this is because I'm not using it correctly.

I note that in your github gist (which doesn't work with the latest version of PragmataPro) [you used a different method to load the ligatures](https://gist.github.com/DeLaGuardo/fe1f3d9397d6ef7468460d54d5601156).

Could you perhaps write a brief tutorial on this please?

Thank you!

**Comment by DeLaGuardo** [comment]
```
(load-file "~/.spacemacs.d/custom/pragmatapro-prettify-symbols.el")
(global-prettify-symbols-mode +1)
(add-hook 'prog-mode-hook
            #'add-pragmatapro-prettify-symbols-alist)
```
Add this lines into your `dotspacemacs/user-config` function in spacemacs init file. Also you need to copy snippet with ligatures bindings into `~/.spacemacs/custom` folder or into any other folder on your choice (change argument for load-file function if needed).

I would like to add instructions into wiki if @fabrizioschiavi does not mind.

**Comment by johnhamelink** [comment]
@DeLaGuardo that works beautifully for me. Thank you!

**Pull request merged**
